"""create sources table

Revision ID: 11a115512a41
Revises: 566effc32951
Create Date: 2026-07-15 08:52:02.428534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a115512a41'
down_revision: Union[str, Sequence[str], None] = '566effc32951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('sport', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('use_browser', sa.Boolean(), nullable=False),
    sa.Column('ignore_https_errors', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_url'), 'sources', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_url'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
