"""add import runs

Revision ID: 4aca1b76c37d
Revises: 11a115512a41
Create Date: 2026-07-15 09:05:57.490760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aca1b76c37d'
down_revision: Union[str, Sequence[str], None] = '11a115512a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='import_status', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_created', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('items_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_runs_id'), 'import_runs', ['id'], unique=False)
    op.create_index(op.f('ix_import_runs_source_id'), 'import_runs', ['source_id'], unique=False)
    op.create_index(op.f('ix_import_runs_status'), 'import_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_runs_status'), table_name='import_runs')
    op.drop_index(op.f('ix_import_runs_source_id'), table_name='import_runs')
    op.drop_index(op.f('ix_import_runs_id'), table_name='import_runs')
    op.drop_table('import_runs')
    # ### end Alembic commands ###
