"""remove unique source url

Revision ID: 566effc32951
Revises: d75f40a86cd5
Create Date: 2026-07-15 08:23:41.307513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566effc32951'
down_revision: Union[str, Sequence[str], None] = 'd75f40a86cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sport_events_source_url'), table_name='sport_events')
    op.create_index(op.f('ix_sport_events_source_url'), 'sport_events', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sport_events_source_url'), table_name='sport_events')
    op.create_index(op.f('ix_sport_events_source_url'), 'sport_events', ['source_url'], unique=True)
    # ### end Alembic commands ###
