"""add deduplication key

Revision ID: d75f40a86cd5
Revises: 8f2b2d18b207
Create Date: 2026-07-15 08:04:43.073988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75f40a86cd5'
down_revision: Union[str, Sequence[str], None] = '8f2b2d18b207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_events', sa.Column('deduplication_key', sa.String(length=64), nullable=True))
    op.drop_constraint(op.f('uq_sport_events_source_external_start'), 'sport_events', type_='unique')
    op.create_index(op.f('ix_sport_events_deduplication_key'), 'sport_events', ['deduplication_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sport_events_deduplication_key'), table_name='sport_events')
    op.create_unique_constraint(op.f('uq_sport_events_source_external_start'), 'sport_events', ['source_name', 'external_id', 'start_date'], postgresql_nulls_not_distinct=False)
    op.drop_column('sport_events', 'deduplication_key')
    # ### end Alembic commands ###
