import { assignNomenclatureCharacteristic, createCharacteristicOption, deleteNomenclatureMedia, generateNomenclatureVariants, toggleNomenclatureVariant, updateNomenclatureMedia, uploadNomenclatureMedia } from "@/app/(workspace)/settings/catalogs/nomenclature/characteristics-actions";
import type { CategoryCharacteristic, CharacteristicDefinition, CharacteristicOption, NomenclatureCharacteristic, NomenclatureMedia, NomenclatureVariant } from "@/lib/nomenclature";

export function NomenclatureCharacteristicsPanel({ itemId, definitions, categoryCharacteristics, assignments, variants, options, media }: { itemId: number; definitions: CharacteristicDefinition[]; categoryCharacteristics: CategoryCharacteristic[]; assignments: NomenclatureCharacteristic[]; variants: NomenclatureVariant[]; options: Record<number, CharacteristicOption[]>; media: NomenclatureMedia[] }) {
  return <section className="mt-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-3 text-lg font-semibold">Характеристики и варианты</h2><div className="space-y-2 text-sm">{assignments.length ? assignments.map((assignment) => <div key={assignment.id} className="rounded border p-2"><b>{definitions.find((definition) => definition.id === assignment.characteristic_id)?.name ?? `Характеристика #${assignment.characteristic_id}`}</b><div className="text-xs text-slate-500">{(options[assignment.characteristic_id] ?? []).filter((option) => option.is_active).map((option) => option.label).join(", ") || "Значения ещё не заведены"}</div></div>) : <p className="text-slate-500">Характеристики не назначены.</p>}
    <form action={assignNomenclatureCharacteristic} className="flex flex-wrap gap-2"><input type="hidden" name="nomenclature_id" value={itemId}/><select name="characteristic_id" required className="rounded border px-2 py-1"><option value="">Добавить характеристику</option>{categoryCharacteristics.filter((row) => !assignments.some((assignment) => assignment.characteristic_id === row.characteristic_id)).map((row) => <option key={row.characteristic_id} value={row.characteristic_id}>{definitions.find((definition) => definition.id === row.characteristic_id)?.name}</option>)}</select><button className="rounded bg-blue-700 px-3 py-1 text-white">Назначить</button></form>
    <form action={createCharacteristicOption} className="flex flex-wrap gap-2"><input type="hidden" name="nomenclature_id" value={itemId}/><select name="characteristic_id" required className="rounded border px-2 py-1">{definitions.filter((definition) => definition.is_active).map((definition) => <option key={definition.id} value={definition.id}>{definition.name}</option>)}</select><input name="code" placeholder="Код значения" required className="rounded border px-2 py-1"/><input name="label" placeholder="Название значения" required className="rounded border px-2 py-1"/><button className="rounded border px-3 py-1">Добавить значение</button></form>
    <form action={generateNomenclatureVariants} className="flex flex-wrap gap-2"><input type="hidden" name="nomenclature_id" value={itemId}/><input name="article_prefix" placeholder="Префикс артикула" required className="rounded border px-2 py-1"/><button className="rounded border px-3 py-1">Сгенерировать варианты</button></form>
    {variants.map((variant) => <div key={variant.id} className="flex flex-wrap items-center justify-between gap-2 rounded border px-2 py-1"><span><b>{variant.article}</b> — {variant.name} <span className="text-xs text-slate-500">{variant.is_active ? "активен" : "архив"}</span></span><form action={toggleNomenclatureVariant}><input type="hidden" name="variant_id" value={variant.id}/><input type="hidden" name="nomenclature_id" value={itemId}/><input type="hidden" name="is_active" value={String(variant.is_active)}/><button className="text-xs text-blue-700">{variant.is_active ? "Деактивировать" : "Активировать"}</button></form></div>)}
    <h3 className="mt-4 font-semibold">Изображения</h3><form action={uploadNomenclatureMedia} className="flex flex-wrap gap-2"><input type="hidden" name="nomenclature_id" value={itemId}/><input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/svg+xml" required className="max-w-full text-sm"/><input name="alt_text" placeholder="Alt-текст" className="rounded border px-2 py-1"/><label className="flex items-center gap-1"><input type="checkbox" name="is_primary" value="true"/> Главное</label><button className="rounded border px-3 py-1">Загрузить</button></form>{media.map((image) => <div key={image.id} className="flex flex-wrap items-center gap-2 rounded border p-2"><img src={`${process.env.NEXT_PUBLIC_SPORT_LEADS_API_URL ?? "http://127.0.0.1:8000"}${image.content_url}`} alt={image.alt_text ?? image.filename} className="h-12 w-12 rounded object-cover"/><span className="min-w-0 flex-1 truncate">{image.filename}{image.is_primary ? " · главное" : ""}</span><form action={updateNomenclatureMedia} className="flex gap-1"><input type="hidden" name="nomenclature_id" value={itemId}/><input type="hidden" name="media_id" value={image.id}/><input name="sort_order" type="number" min="0" defaultValue={image.sort_order} className="w-16 rounded border px-1"/><input type="hidden" name="is_primary" value="true"/><button className="text-xs text-blue-700">Порядок</button></form><form action={deleteNomenclatureMedia}><input type="hidden" name="nomenclature_id" value={itemId}/><input type="hidden" name="media_id" value={image.id}/><button className="text-xs text-red-700">Удалить</button></form></div>)}</div></section>;
}
