"use server";
import { revalidatePath } from "next/cache";
import type { NomenclatureMedia } from "@/lib/nomenclature";
const apiBase = () => (process.env.SPORT_LEADS_API_URL ?? "http://127.0.0.1:8000").replace(/\/$/, "");
const base = () => `${apiBase()}/characteristics`;
const mediaBase = () => apiBase();
async function request(path: string, method: string, body: unknown) { const response = await fetch(`${base()}${path}`, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body), cache: "no-store" }); if (!response.ok) { const data = await response.json().catch(() => null) as { detail?: string } | null; throw new Error(data?.detail ?? `Backend вернул ${response.status}`); } }
export async function createCharacteristic(formData: FormData) { await request("/definitions", "POST", { code: String(formData.get("code") ?? "").trim() || null, name: String(formData.get("name")), kind: String(formData.get("kind") ?? "LIST") }); revalidatePath("/settings/catalogs/product-characteristics"); }
export async function updateCharacteristic(formData: FormData) { await request(`/definitions/${formData.get("id")}`, "PATCH", { name: String(formData.get("name")), is_active: formData.get("is_active") === "true" }); revalidatePath("/settings/catalogs/product-characteristics"); }
export async function createCharacteristicOption(formData: FormData) { await request(`/definitions/${formData.get("characteristic_id")}/options`, "POST", { code: String(formData.get("code")), label: String(formData.get("label")), hex_value: String(formData.get("hex_value") ?? "").trim() || null }); revalidatePath(`/settings/catalogs/product-characteristics/${formData.get("characteristic_id")}`); }
export async function updateCharacteristicOption(formData: FormData) { await request(`/options/${formData.get("id")}`, "PATCH", { label: String(formData.get("label")), sort_order: Number(formData.get("sort_order") ?? 0), hex_value: String(formData.get("hex_value") ?? "").trim() || null, is_active: formData.get("is_active") === "true" }); revalidatePath(`/settings/catalogs/product-characteristics/${formData.get("characteristic_id")}`); }
export async function assignNomenclatureCharacteristic(formData: FormData) { await request(`/nomenclatures/${formData.get("nomenclature_id")}`, "POST", { characteristic_id: Number(formData.get("characteristic_id")) }); revalidatePath(`/settings/catalogs/nomenclature/${formData.get("nomenclature_id")}`); }
export async function generateNomenclatureVariants(formData: FormData) { await request(`/nomenclatures/${formData.get("nomenclature_id")}/variants/generate`, "POST", { article_prefix: String(formData.get("article_prefix")) }); revalidatePath(`/settings/catalogs/nomenclature/${formData.get("nomenclature_id")}`); }
export async function toggleNomenclatureVariant(formData: FormData) { await request(`/variants/${formData.get("variant_id")}`, "PATCH", { is_active: formData.get("is_active") !== "true" }); revalidatePath(`/settings/catalogs/nomenclature/${formData.get("nomenclature_id")}`); }
export async function uploadNomenclatureMedia(formData: FormData) { const file = formData.get("file"); if (!(file instanceof File) || file.size === 0) throw new Error("Выберите файл изображения"); if (file.size > 10 * 1024 * 1024) throw new Error("Размер изображения не должен превышать 10 МБ"); const bytes = Buffer.from(await file.arrayBuffer()).toString("base64"); const response = await fetch(`${mediaBase()}/nomenclatures/${formData.get("nomenclature_id")}/media`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ filename: file.name, mime_type: file.type, content_base64: bytes, alt_text: String(formData.get("alt_text") ?? "") || null, sort_order: Number(formData.get("sort_order") ?? 0), is_primary: formData.get("is_primary") === "true" }), cache: "no-store" }); if (!response.ok) { const data = await response.json().catch(() => null) as { detail?: string } | null; throw new Error(data?.detail ?? `Backend вернул ${response.status}`); } const created = await response.json() as NomenclatureMedia; revalidatePath(`/settings/catalogs/nomenclature/${formData.get("nomenclature_id")}`); return created; }
export async function deleteNomenclatureMedia(formData: FormData) { const response = await fetch(`${mediaBase()}/nomenclatures/${formData.get("nomenclature_id")}/media/${formData.get("media_id")}`, { method: "DELETE", cache: "no-store" }); if (!response.ok) throw new Error(`Backend вернул ${response.status}`); revalidatePath(`/settings/catalogs/nomenclature/${formData.get("nomenclature_id")}`); }
export async function updateNomenclatureMedia(formData: FormData) { const response = await fetch(`${mediaBase()}/nomenclatures/${formData.get("nomenclature_id")}/media/${formData.get("media_id")}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ sort_order: Number(formData.get("sort_order") ?? 0), is_primary: formData.get("is_primary") === "true", alt_text: String(formData.get("alt_text") ?? "") || null }), cache: "no-store" }); if (!response.ok) { const data = await response.json().catch(() => null) as { detail?: string } | null; throw new Error(data?.detail ?? `Backend вернул ${response.status}`); } revalidatePath(`/settings/catalogs/nomenclature/${formData.get("nomenclature_id")}`); }
