"""add unique source url

Revision ID: 8072b8450c96
Revises: 1d9a86fbb15e
Create Date: 2026-07-14 12:11:12.848053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8072b8450c96'
down_revision: Union[str, Sequence[str], None] = '1d9a86fbb15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sport_events_source_url'), 'sport_events', ['source_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sport_events_source_url'), table_name='sport_events')
    # ### end Alembic commands ###
