"""add event import identity fields

Revision ID: 8f2b2d18b207
Revises: 8072b8450c96
Create Date: 2026-07-15 07:33:40.194325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2b2d18b207'
down_revision: Union[str, Sequence[str], None] = '8072b8450c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_events', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('sport_events', sa.Column('source_document_url', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_sport_events_external_id'), 'sport_events', ['external_id'], unique=False)
    op.create_unique_constraint('uq_sport_events_source_external_start', 'sport_events', ['source_name', 'external_id', 'start_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sport_events_source_external_start', 'sport_events', type_='unique')
    op.drop_index(op.f('ix_sport_events_external_id'), table_name='sport_events')
    op.drop_column('sport_events', 'source_document_url')
    op.drop_column('sport_events', 'external_id')
    # ### end Alembic commands ###
